[window.padding]
x = 10
y = 10

[font]
size = 13

[font.normal]
family = "Hack Nerd Font"
style = "Bold"

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[colors.primary]
background = "#1a1b26"
foreground = "#ffffff"
dim_foreground = "#ffffff"
bright_foreground = "#ffffff"

[colors.cursor]
text = "#1a1b26"
cursor = "#888888"

[colors.normal]
black = "#888888"
red = "#ff0000"
green = "#00ff00"
yellow = "#ffff00"
blue = "#00aaff"
magenta = "#ff00ff"
cyan = "#00ffff"
white = "#ffffff"

[colors.bright]
black = "#888888"
red = "#ff0000"
green = "#00ff00"
yellow = "#ffff00"
blue = "#00aaff"
magenta = "#ff00ff"
cyan = "#00ffff"
white = "#ffffff"

[colors.dim]
black = "#888888"
red = "#ff0000"
green = "#00ff00"
yellow = "#ffff00"
blue = "#00aaff"
magenta = "#ff00ff"
cyan = "#00ffff"
white = "#ffffff"
